(source_text
	(description
		(module_declaration
			(module_ansi_header
				(module_keyword
					'module')
				(module_identifier
					'ram_mux')
				(parameter_port_list
					'#'
					'('
					(parameter_port_declaration
						(parameter_declaration
							'parameter'
							(data_type_or_implicit
								(implicit_data_type))
							(list_of_param_assignments
								(param_assignment
									(parameter_identifier
										'ADDR_WIDTH')
									'='
									(constant_param_expression
										(constant_mintypmax_expression
											(constant_expression
												(constant_primary
													(primary_literal
														(number
															(integral_number
																'32')))))))))))
					','
					(parameter_port_declaration
						(parameter_declaration
							'parameter'
							(data_type_or_implicit
								(implicit_data_type))
							(list_of_param_assignments
								(param_assignment
									(parameter_identifier
										'OUT_WIDTH')
									'='
									(constant_param_expression
										(constant_mintypmax_expression
											(constant_expression
												(constant_primary
													(primary_literal
														(number
															(integral_number
																'32')))))))))))
					','
					(parameter_port_declaration
						(parameter_declaration
							'parameter'
							(data_type_or_implicit
								(implicit_data_type))
							(list_of_param_assignments
								(param_assignment
									(parameter_identifier
										'IN0_WIDTH')
									'='
									(constant_param_expression
										(constant_mintypmax_expression
											(constant_expression
												(constant_primary
													(primary_literal
														(number
															(integral_number
																'32')))))))))))
					','
					(parameter_port_declaration
						(parameter_declaration
							'parameter'
							(data_type_or_implicit
								(implicit_data_type))
							(list_of_param_assignments
								(param_assignment
									(parameter_identifier
										'IN1_WIDTH')
									'='
									(constant_param_expression
										(constant_mintypmax_expression
											(constant_expression
												(constant_primary
													(primary_literal
														(number
															(integral_number
																'32')))))))))))
					')')
				(list_of_port_declarations
					'('
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'clk'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'rst_n'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port0_req_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port0_gnt_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port0_rvalid_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'ADDR_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port0_addr_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port0_we_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'IN0_WIDTH'))
																(constant_select)))
														'/'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'8'))))))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port0_be_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'IN0_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port0_rdata_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'IN0_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port0_wdata_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port1_req_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port1_gnt_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port1_rvalid_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'ADDR_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port1_addr_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'port1_we_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'IN1_WIDTH'))
																(constant_select)))
														'/'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'8'))))))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port1_be_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'IN1_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port1_rdata_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'IN1_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'port1_wdata_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'ram_en_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'ADDR_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'ram_addr_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')))))
						(port_identifier
							'ram_we_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'OUT_WIDTH'))
																(constant_select)))
														'/'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'8'))))))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'ram_be_o'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'input')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'OUT_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'ram_rdata_i'))
					','
					(ansi_port_declaration
						(net_port_header
							(port_direction
								'output')
							(net_port_type
								(data_type_or_implicit
									(data_type
										(integer_vector_type
											'logic')
										(packed_dimension
											'['
											(constant_range
												(constant_expression
													(constant_expression
														(constant_primary
															(ps_parameter_identifier
																(parameter_identifier
																	'OUT_WIDTH'))
															(constant_select)))
													'-'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'1'))))))
												':'
												(constant_expression
													(constant_primary
														(primary_literal
															(number
																(integral_number
																	'0'))))))
											']')))))
						(port_identifier
							'ram_wdata_o'))
					')')
				';')
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(local_parameter_declaration
									'localparam'
									(data_type_or_implicit
										(implicit_data_type))
									(list_of_param_assignments
										(param_assignment
											(parameter_identifier
												'IN0_ADDR_HIGH')
											'='
											(constant_param_expression
												(constant_mintypmax_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(system_tf_call
																	'$clog2'
																	'('
																	(list_of_arguments
																		(expression
																			(expression
																				(primary
																					(class_qualifier)
																					(hierarchical_identifier
																						'OUT_WIDTH')
																					(select)))
																			'/'
																			(expression
																				(primary
																					(primary_literal
																						(number
																							(integral_number
																								'8')))))))
																	')')))
														'-'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'1')))))))))))
								';')))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(local_parameter_declaration
									'localparam'
									(data_type_or_implicit
										(implicit_data_type))
									(list_of_param_assignments
										(param_assignment
											(parameter_identifier
												'IN0_ADDR_LOW')
											'='
											(constant_param_expression
												(constant_mintypmax_expression
													(constant_expression
														(constant_primary
															(system_tf_call
																'$clog2'
																'('
																(list_of_arguments
																	(expression
																		(expression
																			(primary
																				(class_qualifier)
																				(hierarchical_identifier
																					'IN0_WIDTH')
																				(select)))
																		'/'
																		(expression
																			(primary
																				(primary_literal
																					(number
																						(integral_number
																							'8')))))))
																')'))))))))
								';')))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(local_parameter_declaration
									'localparam'
									(data_type_or_implicit
										(implicit_data_type))
									(list_of_param_assignments
										(param_assignment
											(parameter_identifier
												'IN0_RATIO')
											'='
											(constant_param_expression
												(constant_mintypmax_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'OUT_WIDTH'))
																(constant_select)))
														'/'
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'IN0_WIDTH'))
																(constant_select)))))))))
								';')))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(data_declaration
									(data_type_or_implicit
										(data_type
											(integer_vector_type
												'logic')
											(packed_dimension
												'['
												(constant_range
													(constant_expression
														(constant_expression
															(constant_expression
																(constant_primary
																	(ps_parameter_identifier
																		(parameter_identifier
																			'OUT_WIDTH'))
																	(constant_select)))
															'/'
															(constant_expression
																(constant_primary
																	(primary_literal
																		(number
																			(integral_number
																				'8'))))))
														'-'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'1'))))))
													':'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'0'))))))
												']')))
									(list_of_variable_decl_assignments
										(variable_decl_assignment
											(variable_identifier
												'port0_be')))
									';'))))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(genvar_declaration
								'genvar'
								(list_of_genvar_identifiers
									(genvar_identifier
										'i0'))
								';')))))
			(non_port_module_item
				(generate_region
					'generate'
					(generate_item
						(module_or_generate_item
							(module_common_item
								(conditional_generate_construct
									(if_generate_construct
										'if'
										'('
										(constant_expression
											(constant_expression
												(constant_primary
													(ps_parameter_identifier
														(parameter_identifier
															'IN0_ADDR_HIGH'))
													(constant_select)))
											'>='
											(constant_expression
												(constant_primary
													(ps_parameter_identifier
														(parameter_identifier
															'IN0_ADDR_LOW'))
													(constant_select))))
										')'
										(generate_block
											'begin'
											(generate_item
												(module_or_generate_item
													(module_common_item
														(module_or_generate_item_declaration
															(package_or_generate_item_declaration
																(data_declaration
																	(data_type_or_implicit
																		(data_type
																			(integer_vector_type
																				'logic')))
																	(list_of_variable_decl_assignments
																		(variable_decl_assignment
																			(variable_identifier
																				'port0_addr_q')))
																	';'))))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(module_or_generate_item_declaration
															(package_or_generate_item_declaration
																(data_declaration
																	(data_type_or_implicit
																		(data_type
																			(integer_vector_type
																				'logic')
																			(packed_dimension
																				'['
																				(constant_range
																					(constant_expression
																						(constant_expression
																							(constant_primary
																								(ps_parameter_identifier
																									(parameter_identifier
																										'IN0_RATIO'))
																								(constant_select)))
																						'-'
																						(constant_expression
																							(constant_primary
																								(primary_literal
																									(number
																										(integral_number
																											'1'))))))
																					':'
																					(constant_expression
																						(constant_primary
																							(primary_literal
																								(number
																									(integral_number
																										'0'))))))
																				']')
																			(packed_dimension
																				'['
																				(constant_range
																					(constant_expression
																						(constant_expression
																							(constant_primary
																								(ps_parameter_identifier
																									(parameter_identifier
																										'IN0_WIDTH'))
																								(constant_select)))
																						'-'
																						(constant_expression
																							(constant_primary
																								(primary_literal
																									(number
																										(integral_number
																											'1'))))))
																					':'
																					(constant_expression
																						(constant_primary
																							(primary_literal
																								(number
																									(integral_number
																										'0'))))))
																				']')))
																	(list_of_variable_decl_assignments
																		(variable_decl_assignment
																			(variable_identifier
																				'port0_rdata')))
																	';'))))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(always_construct
															(always_keyword
																'always_ff')
															(statement
																(statement_item
																	(procedural_timing_control_statement
																		(procedural_timing_control
																			(event_control
																				'@'
																				'('
																				(event_expression
																					(event_expression
																						(edge_identifier
																							'posedge')
																						(expression
																							(primary
																								(class_qualifier)
																								(hierarchical_identifier
																									'clk')
																								(select))))
																					','
																					(event_expression
																						(edge_identifier
																							'negedge')
																						(expression
																							(primary
																								(class_qualifier)
																								(hierarchical_identifier
																									'rst_n')
																								(select)))))
																				')'))
																		(statement_or_null
																			(statement
																				(statement_item
																					(seq_block
																						'begin'
																						(statement_or_null
																							(statement
																								(statement_item
																									(conditional_statement
																										'if'
																										'('
																										(cond_predicate
																											(expression_or_cond_pattern
																												(expression
																													'~'
																													(primary
																														(class_qualifier)
																														(hierarchical_identifier
																															'rst_n')
																														(select)))))
																										')'
																										(statement_or_null
																											(statement
																												(statement_item
																													(nonblocking_assignment
																														(variable_lvalue
																															(hierarchical_variable_identifier
																																(hierarchical_identifier
																																	'port0_addr_q'))
																															(select))
																														'<='
																														(expression
																															(primary
																																(primary_literal
																																	'\'0'))))
																													';')))
																										'else'
																										'if'
																										'('
																										(cond_predicate
																											(expression_or_cond_pattern
																												(expression
																													(primary
																														(class_qualifier)
																														(hierarchical_identifier
																															'port0_gnt_o')
																														(select)))))
																										')'
																										(statement_or_null
																											(statement
																												(statement_item
																													(nonblocking_assignment
																														(variable_lvalue
																															(hierarchical_variable_identifier
																																(hierarchical_identifier
																																	'port0_addr_q'))
																															(select))
																														'<='
																														(expression
																															(primary
																																(class_qualifier)
																																(hierarchical_identifier
																																	'port0_addr_i')
																																(select
																																	'['
																																	(part_select_range
																																		(constant_range
																																			(constant_expression
																																				(constant_primary
																																					(ps_parameter_identifier
																																						(parameter_identifier
																																							'IN0_ADDR_HIGH'))
																																					(constant_select)))
																																			':'
																																			(constant_expression
																																				(constant_primary
																																					(ps_parameter_identifier
																																						(parameter_identifier
																																							'IN0_ADDR_LOW'))
																																					(constant_select)))))
																																	']'))))
																													';')))))))
																						'end')))))))))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(loop_generate_construct
															'for'
															'('
															(genvar_initialization
																(genvar_identifier
																	'i0')
																'='
																(constant_expression
																	(constant_primary
																		(primary_literal
																			(number
																				(integral_number
																					'0'))))))
															';'
															(genvar_expression
																(constant_expression
																	(constant_expression
																		(constant_primary
																			(ps_parameter_identifier
																				(parameter_identifier
																					'i0'))
																			(constant_select)))
																	'<'
																	(constant_expression
																		(constant_primary
																			(ps_parameter_identifier
																				(parameter_identifier
																					'IN0_RATIO'))
																			(constant_select)))))
															';'
															(genvar_iteration
																(genvar_identifier
																	'i0')
																'++')
															')'
															(generate_block
																'begin'
																(generate_item
																	(module_or_generate_item
																		(module_common_item
																			(continuous_assign
																				'assign'
																				(list_of_net_assignments
																					(net_assignment
																						(net_lvalue
																							(ps_or_hierarchical_net_identifier
																								(net_identifier
																									'port0_be'))
																							(constant_select
																								'['
																								(constant_part_select_range
																									(constant_range
																										(constant_expression
																											(constant_expression
																												(constant_expression
																													(constant_expression
																														(constant_primary
																															'('
																															(constant_mintypmax_expression
																																(constant_expression
																																	(constant_expression
																																		(constant_primary
																																			(ps_parameter_identifier
																																				(parameter_identifier
																																					'i0'))
																																			(constant_select)))
																																	'+'
																																	(constant_expression
																																		(constant_primary
																																			(primary_literal
																																				(number
																																					(integral_number
																																						'1')))))))
																															')'))
																													'*'
																													(constant_expression
																														(constant_primary
																															(ps_parameter_identifier
																																(parameter_identifier
																																	'IN0_WIDTH'))
																															(constant_select))))
																												'/'
																												(constant_expression
																													(constant_primary
																														(primary_literal
																															(number
																																(integral_number
																																	'8'))))))
																											'-'
																											(constant_expression
																												(constant_primary
																													(primary_literal
																														(number
																															(integral_number
																																'1'))))))
																										':'
																										(constant_expression
																											(constant_expression
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'i0'))
																														(constant_select)))
																												'*'
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'IN0_WIDTH'))
																														(constant_select))))
																											'/'
																											(constant_expression
																												(constant_primary
																													(primary_literal
																														(number
																															(integral_number
																																'8'))))))))
																								']'))
																						'='
																						(expression
																							(expression
																								(primary
																									'('
																									(mintypmax_expression
																										(expression
																											(expression
																												(primary
																													(class_qualifier)
																													(hierarchical_identifier
																														'i0')
																													(select)))
																											'=='
																											(expression
																												(primary
																													(class_qualifier)
																													(hierarchical_identifier
																														'port0_addr_i')
																													(select
																														'['
																														(part_select_range
																															(constant_range
																																(constant_expression
																																	(constant_primary
																																		(ps_parameter_identifier
																																			(parameter_identifier
																																				'IN0_ADDR_HIGH'))
																																		(constant_select)))
																																':'
																																(constant_expression
																																	(constant_primary
																																		(ps_parameter_identifier
																																			(parameter_identifier
																																				'IN0_ADDR_LOW'))
																																		(constant_select)))))
																														']')))))
																									')'))
																							'?'
																							(expression
																								(primary
																									(class_qualifier)
																									(hierarchical_identifier
																										'port0_be_i')
																									(select)))
																							':'
																							(expression
																								(primary
																									(primary_literal
																										'\'0'))))))
																				';'))))
																(generate_item
																	(module_or_generate_item
																		(module_common_item
																			(continuous_assign
																				'assign'
																				(list_of_net_assignments
																					(net_assignment
																						(net_lvalue
																							(ps_or_hierarchical_net_identifier
																								(net_identifier
																									'port0_rdata'))
																							(constant_select
																								'['
																								(constant_expression
																									(constant_primary
																										(ps_parameter_identifier
																											(parameter_identifier
																												'i0'))
																										(constant_select)))
																								']'))
																						'='
																						(expression
																							(primary
																								(class_qualifier)
																								(hierarchical_identifier
																									'ram_rdata_i')
																								(select
																									'['
																									(part_select_range
																										(constant_range
																											(constant_expression
																												(constant_expression
																													(constant_expression
																														(constant_primary
																															'('
																															(constant_mintypmax_expression
																																(constant_expression
																																	(constant_expression
																																		(constant_primary
																																			(ps_parameter_identifier
																																				(parameter_identifier
																																					'i0'))
																																			(constant_select)))
																																	'+'
																																	(constant_expression
																																		(constant_primary
																																			(primary_literal
																																				(number
																																					(integral_number
																																						'1')))))))
																															')'))
																													'*'
																													(constant_expression
																														(constant_primary
																															(ps_parameter_identifier
																																(parameter_identifier
																																	'IN0_WIDTH'))
																															(constant_select))))
																												'-'
																												(constant_expression
																													(constant_primary
																														(primary_literal
																															(number
																																(integral_number
																																	'1'))))))
																											':'
																											(constant_expression
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'i0'))
																														(constant_select)))
																												'*'
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'IN0_WIDTH'))
																														(constant_select))))))
																									']')))))
																				';'))))
																'end')))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(continuous_assign
															'assign'
															(list_of_net_assignments
																(net_assignment
																	(net_lvalue
																		(ps_or_hierarchical_net_identifier
																			(net_identifier
																				'port0_rdata_o'))
																		(constant_select))
																	'='
																	(expression
																		(primary
																			(class_qualifier)
																			(hierarchical_identifier
																				'port0_rdata')
																			(select
																				'['
																				(expression
																					(primary
																						(class_qualifier)
																						(hierarchical_identifier
																							'port0_addr_q')
																						(select)))
																				']')))))
															';'))))
											'end')
										'else'
										(generate_block
											'begin'
											(generate_item
												(module_or_generate_item
													(module_common_item
														(continuous_assign
															'assign'
															(list_of_net_assignments
																(net_assignment
																	(net_lvalue
																		(ps_or_hierarchical_net_identifier
																			(net_identifier
																				'port0_be'))
																		(constant_select))
																	'='
																	(expression
																		(primary
																			(class_qualifier)
																			(hierarchical_identifier
																				'port0_be_i')
																			(select)))))
															';'))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(continuous_assign
															'assign'
															(list_of_net_assignments
																(net_assignment
																	(net_lvalue
																		(ps_or_hierarchical_net_identifier
																			(net_identifier
																				'port0_rdata_o'))
																		(constant_select))
																	'='
																	(expression
																		(primary
																			(class_qualifier)
																			(hierarchical_identifier
																				'ram_rdata_i')
																			(select)))))
															';'))))
											'end'))))))
					'endgenerate'))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(local_parameter_declaration
									'localparam'
									(data_type_or_implicit
										(implicit_data_type))
									(list_of_param_assignments
										(param_assignment
											(parameter_identifier
												'IN1_ADDR_HIGH')
											'='
											(constant_param_expression
												(constant_mintypmax_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(system_tf_call
																	'$clog2'
																	'('
																	(list_of_arguments
																		(expression
																			(expression
																				(primary
																					(class_qualifier)
																					(hierarchical_identifier
																						'OUT_WIDTH')
																					(select)))
																			'/'
																			(expression
																				(primary
																					(primary_literal
																						(number
																							(integral_number
																								'8')))))))
																	')')))
														'-'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'1')))))))))))
								';')))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(local_parameter_declaration
									'localparam'
									(data_type_or_implicit
										(implicit_data_type))
									(list_of_param_assignments
										(param_assignment
											(parameter_identifier
												'IN1_ADDR_LOW')
											'='
											(constant_param_expression
												(constant_mintypmax_expression
													(constant_expression
														(constant_primary
															(system_tf_call
																'$clog2'
																'('
																(list_of_arguments
																	(expression
																		(expression
																			(primary
																				(class_qualifier)
																				(hierarchical_identifier
																					'IN1_WIDTH')
																				(select)))
																		'/'
																		(expression
																			(primary
																				(primary_literal
																					(number
																						(integral_number
																							'8')))))))
																')'))))))))
								';')))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(local_parameter_declaration
									'localparam'
									(data_type_or_implicit
										(implicit_data_type))
									(list_of_param_assignments
										(param_assignment
											(parameter_identifier
												'IN1_RATIO')
											'='
											(constant_param_expression
												(constant_mintypmax_expression
													(constant_expression
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'OUT_WIDTH'))
																(constant_select)))
														'/'
														(constant_expression
															(constant_primary
																(ps_parameter_identifier
																	(parameter_identifier
																		'IN1_WIDTH'))
																(constant_select)))))))))
								';')))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(package_or_generate_item_declaration
								(data_declaration
									(data_type_or_implicit
										(data_type
											(integer_vector_type
												'logic')
											(packed_dimension
												'['
												(constant_range
													(constant_expression
														(constant_expression
															(constant_expression
																(constant_primary
																	(ps_parameter_identifier
																		(parameter_identifier
																			'OUT_WIDTH'))
																	(constant_select)))
															'/'
															(constant_expression
																(constant_primary
																	(primary_literal
																		(number
																			(integral_number
																				'8'))))))
														'-'
														(constant_expression
															(constant_primary
																(primary_literal
																	(number
																		(integral_number
																			'1'))))))
													':'
													(constant_expression
														(constant_primary
															(primary_literal
																(number
																	(integral_number
																		'0'))))))
												']')))
									(list_of_variable_decl_assignments
										(variable_decl_assignment
											(variable_identifier
												'port1_be')))
									';'))))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(module_or_generate_item_declaration
							(genvar_declaration
								'genvar'
								(list_of_genvar_identifiers
									(genvar_identifier
										'i1'))
								';')))))
			(non_port_module_item
				(generate_region
					'generate'
					(generate_item
						(module_or_generate_item
							(module_common_item
								(conditional_generate_construct
									(if_generate_construct
										'if'
										'('
										(constant_expression
											(constant_expression
												(constant_primary
													(ps_parameter_identifier
														(parameter_identifier
															'IN1_ADDR_HIGH'))
													(constant_select)))
											'>='
											(constant_expression
												(constant_primary
													(ps_parameter_identifier
														(parameter_identifier
															'IN1_ADDR_LOW'))
													(constant_select))))
										')'
										(generate_block
											'begin'
											(generate_item
												(module_or_generate_item
													(module_common_item
														(module_or_generate_item_declaration
															(package_or_generate_item_declaration
																(data_declaration
																	(data_type_or_implicit
																		(data_type
																			(integer_vector_type
																				'logic')))
																	(list_of_variable_decl_assignments
																		(variable_decl_assignment
																			(variable_identifier
																				'port1_addr_q')))
																	';'))))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(module_or_generate_item_declaration
															(package_or_generate_item_declaration
																(data_declaration
																	(data_type_or_implicit
																		(data_type
																			(integer_vector_type
																				'logic')
																			(packed_dimension
																				'['
																				(constant_range
																					(constant_expression
																						(constant_expression
																							(constant_primary
																								(ps_parameter_identifier
																									(parameter_identifier
																										'IN1_RATIO'))
																								(constant_select)))
																						'-'
																						(constant_expression
																							(constant_primary
																								(primary_literal
																									(number
																										(integral_number
																											'1'))))))
																					':'
																					(constant_expression
																						(constant_primary
																							(primary_literal
																								(number
																									(integral_number
																										'0'))))))
																				']')
																			(packed_dimension
																				'['
																				(constant_range
																					(constant_expression
																						(constant_expression
																							(constant_primary
																								(ps_parameter_identifier
																									(parameter_identifier
																										'IN1_WIDTH'))
																								(constant_select)))
																						'-'
																						(constant_expression
																							(constant_primary
																								(primary_literal
																									(number
																										(integral_number
																											'1'))))))
																					':'
																					(constant_expression
																						(constant_primary
																							(primary_literal
																								(number
																									(integral_number
																										'0'))))))
																				']')))
																	(list_of_variable_decl_assignments
																		(variable_decl_assignment
																			(variable_identifier
																				'port1_rdata')))
																	';'))))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(always_construct
															(always_keyword
																'always_ff')
															(statement
																(statement_item
																	(procedural_timing_control_statement
																		(procedural_timing_control
																			(event_control
																				'@'
																				'('
																				(event_expression
																					(event_expression
																						(edge_identifier
																							'posedge')
																						(expression
																							(primary
																								(class_qualifier)
																								(hierarchical_identifier
																									'clk')
																								(select))))
																					','
																					(event_expression
																						(edge_identifier
																							'negedge')
																						(expression
																							(primary
																								(class_qualifier)
																								(hierarchical_identifier
																									'rst_n')
																								(select)))))
																				')'))
																		(statement_or_null
																			(statement
																				(statement_item
																					(seq_block
																						'begin'
																						(statement_or_null
																							(statement
																								(statement_item
																									(conditional_statement
																										'if'
																										'('
																										(cond_predicate
																											(expression_or_cond_pattern
																												(expression
																													'~'
																													(primary
																														(class_qualifier)
																														(hierarchical_identifier
																															'rst_n')
																														(select)))))
																										')'
																										(statement_or_null
																											(statement
																												(statement_item
																													(nonblocking_assignment
																														(variable_lvalue
																															(hierarchical_variable_identifier
																																(hierarchical_identifier
																																	'port1_addr_q'))
																															(select))
																														'<='
																														(expression
																															(primary
																																(primary_literal
																																	'\'0'))))
																													';')))
																										'else'
																										'if'
																										'('
																										(cond_predicate
																											(expression_or_cond_pattern
																												(expression
																													(primary
																														(class_qualifier)
																														(hierarchical_identifier
																															'port1_gnt_o')
																														(select)))))
																										')'
																										(statement_or_null
																											(statement
																												(statement_item
																													(nonblocking_assignment
																														(variable_lvalue
																															(hierarchical_variable_identifier
																																(hierarchical_identifier
																																	'port1_addr_q'))
																															(select))
																														'<='
																														(expression
																															(primary
																																(class_qualifier)
																																(hierarchical_identifier
																																	'port1_addr_i')
																																(select
																																	'['
																																	(part_select_range
																																		(constant_range
																																			(constant_expression
																																				(constant_primary
																																					(ps_parameter_identifier
																																						(parameter_identifier
																																							'IN1_ADDR_HIGH'))
																																					(constant_select)))
																																			':'
																																			(constant_expression
																																				(constant_primary
																																					(ps_parameter_identifier
																																						(parameter_identifier
																																							'IN1_ADDR_LOW'))
																																					(constant_select)))))
																																	']'))))
																													';')))))))
																						'end')))))))))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(loop_generate_construct
															'for'
															'('
															(genvar_initialization
																(genvar_identifier
																	'i1')
																'='
																(constant_expression
																	(constant_primary
																		(primary_literal
																			(number
																				(integral_number
																					'0'))))))
															';'
															(genvar_expression
																(constant_expression
																	(constant_expression
																		(constant_primary
																			(ps_parameter_identifier
																				(parameter_identifier
																					'i1'))
																			(constant_select)))
																	'<'
																	(constant_expression
																		(constant_expression
																			(constant_primary
																				(ps_parameter_identifier
																					(parameter_identifier
																						'OUT_WIDTH'))
																				(constant_select)))
																		'/'
																		(constant_expression
																			(constant_primary
																				(ps_parameter_identifier
																					(parameter_identifier
																						'IN1_WIDTH'))
																				(constant_select))))))
															';'
															(genvar_iteration
																(genvar_identifier
																	'i1')
																'++')
															')'
															(generate_block
																'begin'
																(generate_item
																	(module_or_generate_item
																		(module_common_item
																			(continuous_assign
																				'assign'
																				(list_of_net_assignments
																					(net_assignment
																						(net_lvalue
																							(ps_or_hierarchical_net_identifier
																								(net_identifier
																									'port1_be'))
																							(constant_select
																								'['
																								(constant_part_select_range
																									(constant_range
																										(constant_expression
																											(constant_expression
																												(constant_expression
																													(constant_expression
																														(constant_primary
																															'('
																															(constant_mintypmax_expression
																																(constant_expression
																																	(constant_expression
																																		(constant_primary
																																			(ps_parameter_identifier
																																				(parameter_identifier
																																					'i1'))
																																			(constant_select)))
																																	'+'
																																	(constant_expression
																																		(constant_primary
																																			(primary_literal
																																				(number
																																					(integral_number
																																						'1')))))))
																															')'))
																													'*'
																													(constant_expression
																														(constant_primary
																															(ps_parameter_identifier
																																(parameter_identifier
																																	'IN1_WIDTH'))
																															(constant_select))))
																												'/'
																												(constant_expression
																													(constant_primary
																														(primary_literal
																															(number
																																(integral_number
																																	'8'))))))
																											'-'
																											(constant_expression
																												(constant_primary
																													(primary_literal
																														(number
																															(integral_number
																																'1'))))))
																										':'
																										(constant_expression
																											(constant_expression
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'i1'))
																														(constant_select)))
																												'*'
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'IN1_WIDTH'))
																														(constant_select))))
																											'/'
																											(constant_expression
																												(constant_primary
																													(primary_literal
																														(number
																															(integral_number
																																'8'))))))))
																								']'))
																						'='
																						(expression
																							(expression
																								(primary
																									'('
																									(mintypmax_expression
																										(expression
																											(expression
																												(primary
																													(class_qualifier)
																													(hierarchical_identifier
																														'i1')
																													(select)))
																											'=='
																											(expression
																												(primary
																													(class_qualifier)
																													(hierarchical_identifier
																														'port1_addr_i')
																													(select
																														'['
																														(part_select_range
																															(constant_range
																																(constant_expression
																																	(constant_primary
																																		(ps_parameter_identifier
																																			(parameter_identifier
																																				'IN1_ADDR_HIGH'))
																																		(constant_select)))
																																':'
																																(constant_expression
																																	(constant_primary
																																		(ps_parameter_identifier
																																			(parameter_identifier
																																				'IN1_ADDR_LOW'))
																																		(constant_select)))))
																														']')))))
																									')'))
																							'?'
																							(expression
																								(primary
																									(class_qualifier)
																									(hierarchical_identifier
																										'port1_be_i')
																									(select)))
																							':'
																							(expression
																								(primary
																									(primary_literal
																										'\'0'))))))
																				';'))))
																(generate_item
																	(module_or_generate_item
																		(module_common_item
																			(continuous_assign
																				'assign'
																				(list_of_net_assignments
																					(net_assignment
																						(net_lvalue
																							(ps_or_hierarchical_net_identifier
																								(net_identifier
																									'port1_rdata'))
																							(constant_select
																								'['
																								(constant_expression
																									(constant_primary
																										(ps_parameter_identifier
																											(parameter_identifier
																												'i1'))
																										(constant_select)))
																								']'))
																						'='
																						(expression
																							(primary
																								(class_qualifier)
																								(hierarchical_identifier
																									'ram_rdata_i')
																								(select
																									'['
																									(part_select_range
																										(constant_range
																											(constant_expression
																												(constant_expression
																													(constant_expression
																														(constant_primary
																															'('
																															(constant_mintypmax_expression
																																(constant_expression
																																	(constant_expression
																																		(constant_primary
																																			(ps_parameter_identifier
																																				(parameter_identifier
																																					'i1'))
																																			(constant_select)))
																																	'+'
																																	(constant_expression
																																		(constant_primary
																																			(primary_literal
																																				(number
																																					(integral_number
																																						'1')))))))
																															')'))
																													'*'
																													(constant_expression
																														(constant_primary
																															(ps_parameter_identifier
																																(parameter_identifier
																																	'IN1_WIDTH'))
																															(constant_select))))
																												'-'
																												(constant_expression
																													(constant_primary
																														(primary_literal
																															(number
																																(integral_number
																																	'1'))))))
																											':'
																											(constant_expression
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'i1'))
																														(constant_select)))
																												'*'
																												(constant_expression
																													(constant_primary
																														(ps_parameter_identifier
																															(parameter_identifier
																																'IN1_WIDTH'))
																														(constant_select))))))
																									']')))))
																				';'))))
																'end')))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(continuous_assign
															'assign'
															(list_of_net_assignments
																(net_assignment
																	(net_lvalue
																		(ps_or_hierarchical_net_identifier
																			(net_identifier
																				'port1_rdata_o'))
																		(constant_select))
																	'='
																	(expression
																		(primary
																			(class_qualifier)
																			(hierarchical_identifier
																				'port1_rdata')
																			(select
																				'['
																				(expression
																					(primary
																						(class_qualifier)
																						(hierarchical_identifier
																							'port1_addr_q')
																						(select)))
																				']')))))
															';'))))
											'end')
										'else'
										(generate_block
											'begin'
											(generate_item
												(module_or_generate_item
													(module_common_item
														(continuous_assign
															'assign'
															(list_of_net_assignments
																(net_assignment
																	(net_lvalue
																		(ps_or_hierarchical_net_identifier
																			(net_identifier
																				'port1_be'))
																		(constant_select))
																	'='
																	(expression
																		(primary
																			(class_qualifier)
																			(hierarchical_identifier
																				'port1_be_i')
																			(select)))))
															';'))))
											(generate_item
												(module_or_generate_item
													(module_common_item
														(continuous_assign
															'assign'
															(list_of_net_assignments
																(net_assignment
																	(net_lvalue
																		(ps_or_hierarchical_net_identifier
																			(net_identifier
																				'port1_rdata_o'))
																		(constant_select))
																	'='
																	(expression
																		(primary
																			(class_qualifier)
																			(hierarchical_identifier
																				'ram_rdata_i')
																			(select)))))
															';'))))
											'end'))))))
					'endgenerate'))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(always_construct
							(always_keyword
								'always_comb')
							(statement
								(statement_item
									(seq_block
										'begin'
										(block_item_declaration
											(data_declaration
												(data_type_or_implicit
													(implicit_data_type))
												(list_of_variable_decl_assignments
													(variable_decl_assignment
														(variable_identifier
															'port0_gnt_o')
														'='
														(expression
															(primary
																(primary_literal
																	(number
																		(integral_number
																			'1\'b0')))))))
												';'))
										(block_item_declaration
											(data_declaration
												(data_type_or_implicit
													(implicit_data_type))
												(list_of_variable_decl_assignments
													(variable_decl_assignment
														(variable_identifier
															'port1_gnt_o')
														'='
														(expression
															(primary
																(primary_literal
																	(number
																		(integral_number
																			'1\'b0')))))))
												';'))
										(statement_or_null
											(statement
												(statement_item
													(conditional_statement
														'if'
														'('
														(cond_predicate
															(expression_or_cond_pattern
																(expression
																	(primary
																		(class_qualifier)
																		(hierarchical_identifier
																			'port0_req_i')
																		(select)))))
														')'
														(statement_or_null
															(statement
																(statement_item
																	(blocking_assignment
																		(operator_assignment
																			(variable_lvalue
																				(hierarchical_variable_identifier
																					(hierarchical_identifier
																						'port0_gnt_o'))
																				(select))
																			(assignment_operator
																				'=')
																			(expression
																				(primary
																					(primary_literal
																						(number
																							(integral_number
																								'1\'b1')))))))
																	';')))
														'else'
														'if'
														'('
														(cond_predicate
															(expression_or_cond_pattern
																(expression
																	(primary
																		(class_qualifier)
																		(hierarchical_identifier
																			'port1_req_i')
																		(select)))))
														')'
														(statement_or_null
															(statement
																(statement_item
																	(blocking_assignment
																		(operator_assignment
																			(variable_lvalue
																				(hierarchical_variable_identifier
																					(hierarchical_identifier
																						'port1_gnt_o'))
																				(select))
																			(assignment_operator
																				'=')
																			(expression
																				(primary
																					(primary_literal
																						(number
																							(integral_number
																								'1\'b1')))))))
																	';')))))))
										'end')))))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(continuous_assign
							'assign'
							(list_of_net_assignments
								(net_assignment
									(net_lvalue
										(ps_or_hierarchical_net_identifier
											(net_identifier
												'ram_en_o'))
										(constant_select))
									'='
									(expression
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_req_i')
												(select)))
										'|'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port1_req_i')
												(select))))))
							';'))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(continuous_assign
							'assign'
							(list_of_net_assignments
								(net_assignment
									(net_lvalue
										(ps_or_hierarchical_net_identifier
											(net_identifier
												'ram_addr_o'))
										(constant_select))
									'='
									(expression
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_req_i')
												(select)))
										'?'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_addr_i')
												(select)))
										':'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port1_addr_i')
												(select))))))
							';'))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(continuous_assign
							'assign'
							(list_of_net_assignments
								(net_assignment
									(net_lvalue
										(ps_or_hierarchical_net_identifier
											(net_identifier
												'ram_wdata_o'))
										(constant_select))
									'='
									(expression
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_req_i')
												(select)))
										'?'
										(expression
											(primary
												(multiple_concatenation
													'{'
													(expression
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'OUT_WIDTH')
																(select)))
														'/'
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'IN0_WIDTH')
																(select))))
													(concatenation
														'{'
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'port0_wdata_i')
																(select)))
														'}')
													'}')))
										':'
										(expression
											(primary
												(multiple_concatenation
													'{'
													(expression
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'OUT_WIDTH')
																(select)))
														'/'
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'IN1_WIDTH')
																(select))))
													(concatenation
														'{'
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'port1_wdata_i')
																(select)))
														'}')
													'}'))))))
							';'))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(continuous_assign
							'assign'
							(list_of_net_assignments
								(net_assignment
									(net_lvalue
										(ps_or_hierarchical_net_identifier
											(net_identifier
												'ram_we_o'))
										(constant_select))
									'='
									(expression
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_req_i')
												(select)))
										'?'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_we_i')
												(select)))
										':'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port1_we_i')
												(select))))))
							';'))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(continuous_assign
							'assign'
							(list_of_net_assignments
								(net_assignment
									(net_lvalue
										(ps_or_hierarchical_net_identifier
											(net_identifier
												'ram_be_o'))
										(constant_select))
									'='
									(expression
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_req_i')
												(select)))
										'?'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port0_be')
												(select)))
										':'
										(expression
											(primary
												(class_qualifier)
												(hierarchical_identifier
													'port1_be')
												(select))))))
							';'))))
			(non_port_module_item
				(module_or_generate_item
					(module_common_item
						(always_construct
							(always_keyword
								'always_ff')
							(statement
								(statement_item
									(procedural_timing_control_statement
										(procedural_timing_control
											(event_control
												'@'
												'('
												(event_expression
													(event_expression
														(edge_identifier
															'posedge')
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'clk')
																(select))))
													','
													(event_expression
														(edge_identifier
															'negedge')
														(expression
															(primary
																(class_qualifier)
																(hierarchical_identifier
																	'rst_n')
																(select)))))
												')'))
										(statement_or_null
											(statement
												(statement_item
													(seq_block
														'begin'
														(statement_or_null
															(statement
																(statement_item
																	(conditional_statement
																		'if'
																		'('
																		(cond_predicate
																			(expression_or_cond_pattern
																				(expression
																					(expression
																						(primary
																							(class_qualifier)
																							(hierarchical_identifier
																								'rst_n')
																							(select)))
																					'=='
																					(expression
																						(primary
																							(primary_literal
																								(number
																									(integral_number
																										'1\'b0'))))))))
																		')'
																		(statement_or_null
																			(statement
																				(statement_item
																					(seq_block
																						'begin'
																						(statement_or_null
																							(statement
																								(statement_item
																									(nonblocking_assignment
																										(variable_lvalue
																											(hierarchical_variable_identifier
																												(hierarchical_identifier
																													'port0_rvalid_o'))
																											(select))
																										'<='
																										(expression
																											(primary
																												(primary_literal
																													(number
																														(integral_number
																															'1\'b0'))))))
																									';')))
																						(statement_or_null
																							(statement
																								(statement_item
																									(nonblocking_assignment
																										(variable_lvalue
																											(hierarchical_variable_identifier
																												(hierarchical_identifier
																													'port1_rvalid_o'))
																											(select))
																										'<='
																										(expression
																											(primary
																												(primary_literal
																													(number
																														(integral_number
																															'1\'b0'))))))
																									';')))
																						'end'))))
																		'else'
																		(statement_or_null
																			(statement
																				(statement_item
																					(seq_block
																						'begin'
																						(statement_or_null
																							(statement
																								(statement_item
																									(nonblocking_assignment
																										(variable_lvalue
																											(hierarchical_variable_identifier
																												(hierarchical_identifier
																													'port0_rvalid_o'))
																											(select))
																										'<='
																										(expression
																											(primary
																												(class_qualifier)
																												(hierarchical_identifier
																													'port0_gnt_o')
																												(select))))
																									';')))
																						(statement_or_null
																							(statement
																								(statement_item
																									(nonblocking_assignment
																										(variable_lvalue
																											(hierarchical_variable_identifier
																												(hierarchical_identifier
																													'port1_rvalid_o'))
																											(select))
																										'<='
																										(expression
																											(primary
																												(class_qualifier)
																												(hierarchical_identifier
																													'port1_gnt_o')
																												(select))))
																									';')))
																						'end'))))))))
														'end')))))))))))
			'endmodule'))
	'<EOF>')
